name: cron workflow

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
    - cron: "20 1 * * *"   # At 1:20 AM daily
  workflow_dispatch:        # Allow manual triggering

jobs:
  cron-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "cron workflow triggered"
